a = 1;
true;
1 + 2;
true || false && true;
if false then true else false;
if (true || false) then 1 + 2 else 100;
1 + 2 * 3 + 4 / 5 - 6;
1 + true;
20 & 10;
true + false;
true && false;
true && 1;
(\n : Int . n * n + 1) 100;
(\n : Int . n) false;
(\x : Bool . x) true;
(\x : Bool . x) if false then true else false;
a = (\x : Bool . x);
a true;
id = (\x : Bool . x);
id false;
b = (\x : Bool . x);
b true;
b false true;
(\x:Bool . \x:Bool . x) true false true false;

